"""empty message

Revision ID: 878c3cbc01e4
Revises: None
Create Date: 2016-09-17 09:28:36.707231

"""

# revision identifiers, used by Alembic.
revision = '878c3cbc01e4'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('match', postgresql.JSON(), nullable=True),
    sa.Column('result', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    ### end Alembic commands ###
